before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: MeZMjm82rw25AQ8wk+L8bNKnJZo+J+V3jcyByVSGqypKPq78fFFeMik7EY/81WpqYX+2yvpp0d4c60vTl/ymkut2XXHcHtlvNaiw6xrUmWsopNS1THiA+AwWIQEYOyhXxkH6gOKkwsK0PN4Vhd6iCOaIrdjwwbl02O82ZsqXoVuiRyFqKKEpkLS0DXu/KqPH43HeMKS0Ft1RU5yirvGb87SWcR3aT+gIo/PApNwY2sAfbPglI8PDu1NCu28TowmhpULrCfBbc3GbfCm47VC0u3EeFvGYpJCu3/loajdKIWltwaZF7/Vnzgwd/Dv2jLzMGOOXa9u9ZXXFl3Gr1ciC83H6Oe3yGuXOwuP9w577cAIlusLT4Z0we4J0WCdqunSa26YhIYaYLk3/c6ZkgEmvEdTMCL3VsvtaZqiAubdVmaOmT4BlaOuaKoqnUKiiNYDzF2pc93zng0YI3C6mf1Uh2/YuJHeNvAbsNmusklps6qZj2REHlRx4RW94FeugHVGmR6QyDiOyqVSFrYD4YoNOGJpLmzeNctclzx5GNvLKAIwB+rNWUZm42Riry90J3y8eo1jxZV0uMgMiRXZKpeJ2ro1Lj83CqaIpDbRJp0sRVvpfcjXZYkR45d1IKIqnKjS1xQ/7aLixjiIUz6GW0wsoy0d3L/i2GUn6pUWy88xF/cg= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
